import "@repo/ui/styles.css";
import "./globals.css";
import { TopBar } from "@repo/ui";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { QueryProvider } from "@/shared/providers/query-provider";
import { ThemeProvider } from "@/shared/providers/theme-provider";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" suppressHydrationWarning>
      <body className={geist.className}>
        <ThemeProvider>
          <TopBar>
            <span className="truncate text-sm font-medium text-foreground">
              Open Router Sessions
            </span>
          </TopBar>
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
