import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { QueryProvider } from "@/shared/providers/query-provider";
import { ThemeProvider } from "@/shared/providers/theme-provider";
import { WebTopBar } from "@/shared/shell/ui/web-top-bar";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk" suppressHydrationWarning>
      <body className={geist.className}>
        <ThemeProvider>
          <div className="min-h-dvh">
            <header className="sticky top-0 z-50">
              <WebTopBar />
            </header>
            <main className="h-[calc(100dvh-var(--header-mobile-height))] min-h-0 flex-1 overflow-x-clip overflow-y-auto sm:h-[calc(100dvh-var(--header-tablet-height))] md:h-[calc(100dvh-var(--header-height))]">
              <QueryProvider>{children}</QueryProvider>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
